"""Layer 2 — YOLOv8 Specialist.

Responsibilities
----------------
- Classify and localise defects in frames flagged by Layer 1.
- Trained on pseudo-labels generated by GPT-4o (Layer 3 offline mode).
- If prediction confidence ≥ 0.85 → log defect and end cascade.
- If prediction confidence < 0.85  → escalate to Layer 3 (GPT-4o).
"""
